name: face-cluster-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - pip
  - pip:
    - ultralytics
    - easyocr
    # Provides the cv2 module used by the scripts
    - opencv-python
    - matplotlib
    - scikit-learn
    - insightface
    - onnxruntime
    - pre-commit
    - torch
    - torchvision
    - gdown
    - tensorboard
    - hdbscan
    - streamlit
